image: maven:latest

stages:
  - build
  - test
  - package
  - production

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn -DskipTests=true package
  artifacts:
    paths:
      - target/*.jar


production:
  stage: production
  image: zenika/kotlin
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - main
